version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: path-test-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testpath
    # ports:
    #   - "3306:3306"
    volumes:
      - ./app/src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - path-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: path-test
    ports:
      - "8083:8083"
    volumes:
      - .:/workspace
      - /workspace/app/target:/workspace/app/target
    environment:
      - SERVER_PORT=8083
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/testpath?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - path-network

networks:
  path-network:
    driver: bridge
